spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: abc123
    type: org.apache.commons.dbcp2.BasicDataSource

    
a-name: 张三
b-name: 李四